### ISSUE TITLE
Feature request: strategize session creation

### ISSUE THREAD

**Issue by jamesarosen** [brandonpittman/remix-pages-context#2]
I have a Remix app that runs on Cloudflare and needs the Cloudflare ENV vars, but uses something other than Cloudflare KV for sessions. I'd love to be able to use this library but customize the session-generator logic.

I had written up a [proposal](https://github.com/jamesarosen/remix-auto-session) for a project that does something similar. I'm happy to contribute those ideas here or otherwise join forces.

**Comment by brandonpittman** [comment]
I can make the session optional. It was in the first version.

**Comment by brandonpittman** [comment]
Not what you want, probably, but `v1.0.3` makes the `sessionSchema` optional. Will hold off on any other big changes until Remix's `beforeLoader` or whatever the API will be change happens.

Closed by https://github.com/brandonpittman/remix-pages-context/commit/dfd58524554b47c07c165dd1708dd4b448b07fc1#diff-a2a171449d862fe29692ce031981047d7ab755ae7f84c707aef80701b3ea0c80
